#!/usr/bin/env bash
###############################################################################
# generate-project-bundle.sh — DEPRECATED (2026-03-08)
###############################################################################
# Replaced by generate-reference-docs.sh which creates focused split files
# under /workspace/reference/ instead of a single 607KB monolith.
#
# This script is kept for backwards compatibility but is no longer called
# by deploy.sh. To generate the old monolithic bundle, run manually:
#   bash scripts/generate-project-bundle.sh
###############################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
cd "$REPO_DIR"

OUT="workspace/project-bundle.md"

cat > "$OUT" << 'HEADER'
# in-fused.org — Complete Project Bundle

> **Auto-generated reference.** Contains every file in the project.
> Agents: `read(path: "/workspace/project-bundle.md")` to access this.
> URL: `https://in-fused.org/workspace/project-bundle.md`
> Repo: `https://github.com/in-fused/VPS`

## Table of Contents

| Section | File | Lines | Purpose |
|---------|------|-------|---------|
| 1 | CLAUDE.md | ~820 | Master project docs, architecture, config reference |
| 2 | docker-compose.yml | ~297 | Docker stack definition (8 services) |
| 3 | Caddyfile | ~311 | Reverse proxy, auth, routing |
| 4 | litellm_config.yaml | ~461 | 27+ models across 8 cost tiers |
| 5 | scripts/deploy.sh | ~307 | Stack deployment script |
| 6 | scripts/openclaw-entrypoint.sh | ~30 | OpenClaw container startup |
| 7 | scripts/caddy-entrypoint.sh | ~36 | Auth token generation |
| 8 | scripts/seed-agent-workspaces.js | ~690 | Agent workspace file seeder |
| 9 | scripts/auto-kickoff.js | ~145 | Auto-startup message to leads |
| 10 | scrapling/api.py | ~204 | Web scraping API |
| 11 | workspace/js/app.js | ~4227 | Alpine stores, chat, governance |
| 12 | workspace/js/workflow.js | ~1274 | LiteGraph nodes, executor |
| 13 | workspace/js/workflow-bridge.js | ~530 | Agent↔workflow bridge |
| 14 | workspace/js/openclaw-client.js | ~724 | OpenClaw WebSocket RPC client |
| 15 | workspace/index.html | ~2376 | Mission Control SPA shell |
| 16 | workspace/css/styles.css | ~720 | Custom styles |

---

HEADER

# Function to append a file with section header
append_file() {
  local num="$1"
  local filepath="$2"
  local desc="$3"

  local lines
  lines=$(wc -l < "$filepath")

  echo "" >> "$OUT"
  echo "# [$num] $filepath ($lines lines) — $desc" >> "$OUT"
  echo "" >> "$OUT"
  echo '```' >> "$OUT"
  cat "$filepath" >> "$OUT"
  echo '```' >> "$OUT"
  echo "" >> "$OUT"
  echo "---" >> "$OUT"
}

# Append all project files
append_file 1  "CLAUDE.md"                         "Master project documentation"
append_file 2  "docker-compose.yml"                "Docker stack (8 services)"
append_file 3  "Caddyfile"                         "Reverse proxy config"
append_file 4  "litellm_config.yaml"               "Model routing (27+ models)"
append_file 5  "scripts/deploy.sh"                 "Deployment script"
append_file 6  "scripts/openclaw-entrypoint.sh"    "OpenClaw startup"
append_file 7  "scripts/caddy-entrypoint.sh"       "Auth token generation"
append_file 8  "scripts/seed-agent-workspaces.js"  "Agent workspace seeder"
append_file 9  "scripts/auto-kickoff.js"           "Auto-startup for leads"
append_file 10 "scrapling/api.py"                  "Web scraping API"
append_file 11 "workspace/js/app.js"               "Alpine stores + chat + governance"
append_file 12 "workspace/js/workflow.js"           "LiteGraph nodes + executor"
append_file 13 "workspace/js/workflow-bridge.js"    "Agent workflow bridge"
append_file 14 "workspace/js/openclaw-client.js"    "OpenClaw WS RPC client"
append_file 15 "workspace/index.html"              "Mission Control SPA"
append_file 16 "workspace/css/styles.css"           "Custom styles"

# Footer
cat >> "$OUT" << 'FOOTER'

# End of Project Bundle

Generated by `scripts/generate-project-bundle.sh`. To regenerate:
```
cd /home/VPS && bash scripts/generate-project-bundle.sh
```

## Agent Access

**From inside OpenClaw container:**
```
read(path: "/workspace/project-bundle.md")
```

**Via URL (requires auth cookie):**
```
https://in-fused.org/workspace/project-bundle.md
```

**Clone the repo (requires git + GitHub access):**
```
# If repo is public:
exec wget -qO /tmp/repo.tar.gz https://github.com/in-fused/VPS/archive/refs/heads/main.tar.gz
exec tar xzf /tmp/repo.tar.gz -C /tmp/

# With a GitHub token:
exec wget --header="Authorization: token <GITHUB_TOKEN>" -qO /tmp/repo.tar.gz https://github.com/in-fused/VPS/archive/refs/heads/main.tar.gz
```
FOOTER

TOTAL=$(wc -l < "$OUT")
echo "[bundle] Generated $OUT ($TOTAL lines)"
